FROM docker.io/oven/bun:1.1.34-alpine AS deps
WORKDIR /app
COPY web/package.json /app/package.json
RUN bun install

FROM docker.io/oven/bun:1.1.34-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules /app/node_modules
COPY web /app
RUN bun run build

FROM docker.io/oven/bun:1.1.34-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/.next/standalone /app
COPY --from=build /app/.next/static /app/.next/static
COPY --from=build /app/public /app/public

EXPOSE 3000
CMD ["bun", "server.js"]
