FROM docker.io/oven/bun:1.1.34-alpine

WORKDIR /app

COPY api/package.json /app/package.json
RUN bun install

COPY api/src /app/src
COPY api/openapi.json /app/openapi.json

EXPOSE 3001
CMD ["bun", "run", "start"]
